/**
 * End-to-end integration test for the Routine creation flow.
 *
 * Exercises the full Routine UI path in sequence:
 *   1. createWithCreationTask — creates draft routine + routine-session channel,
 *      sends kickoff to the ORIGINAL bot's session (no clone agent)
 *   2. update — simulates agent refinement (title, documentContent, triggers)
 *   3. completeCreation — transitions to upcoming, archives the creation channel
 *
 * This is a mock-based test (no real DB). The key thing it verifies that
 * individual unit tests don't: the routineId returned from createWithCreationTask
 * flows correctly into update and completeCreation, and the session ID uses the
 * original bot's agentId (matching what post-broadcast derives).
 */

import { jest, describe, it, expect, beforeEach } from '@jest/globals';
import { Test, TestingModule } from '@nestjs/testing';
import { RoutinesService } from '../routines.service.js';
import { TaskCastService } from '../taskcast.service.js';
import { DATABASE_CONNECTION } from '@team9/database';
import { DocumentsService } from '../../documents/documents.service.js';
import { ChannelsService } from '../../im/channels/channels.service.js';
import { ClawHiveService } from '@team9/claw-hive';
import { BotService } from '../../bot/bot.service.js';
import { RoutineTriggersService } from '../routine-triggers.service.js';
import { AmqpConnection } from '@team9/rabbitmq';
import { WEBSOCKET_GATEWAY } from '../../shared/constants/injection-tokens.js';
import { UsersService } from '../../im/users/users.service.js';
import { Folder9ClientService } from '../../wikis/folder9-client.service.js';

// ── helpers ──────────────────────────────────────────────────────────

type MockFn = jest.Mock<(...args: any[]) => any>;

function mockDb() {
  const chain: Record<string, MockFn> = {};
  const methods = [
    'select',
    'from',
    'where',
    'limit',
    'insert',
    'values',
    'returning',
    'update',
    'set',
    'and',
    'orderBy',
    'desc',
    'delete',
    'leftJoin',
    'innerJoin',
    // SELECT ... FOR UPDATE — used by ensureRoutineFolder, which A.5
    // wires into completeCreation.
    'for',
  ];
  for (const m of methods) {
    chain[m] = jest.fn<any>().mockReturnValue(chain);
  }
  chain.limit.mockResolvedValue([]);
  chain.returning.mockResolvedValue([]);
  chain.for.mockResolvedValue([]);
  // `transaction(cb)` invokes the callback with the same chain as tx and
  // returns whatever the callback returns. Mirrors the unit-spec mock.
  chain.transaction = jest
    .fn<any>()
    .mockImplementation((cb: (tx: any) => any) => cb(chain));
  return chain;
}

// ── fixtures ─────────────────────────────────────────────────────────

const ROUTINE_ID = 'routine-flow-1';
const TENANT_ID = 'tenant-1';
const USER_ID = 'user-1';
const CHANNEL_ID = 'channel-flow-1';
const AGENT_ID = 'source-agent-id';
// Session ID uses the original bot's agentId (not a clone)
const SESSION_ID = `team9/${TENANT_ID}/${AGENT_ID}/dm/${CHANNEL_ID}`;

const SOURCE_BOT = {
  userId: 'bot-user-1',
  botId: 'bot-1',
  username: 'my-bot',
  displayName: 'My Bot',
  email: 'bot@team9.local',
  type: 'custom',
  ownerId: 'owner-1',
  mentorId: null,
  description: null,
  capabilities: null,
  extra: null,
  managedProvider: 'hive',
  managedMeta: { agentId: AGENT_ID },
  isActive: true,
};

/** Draft routine returned from db.insert().values().returning() */
const DRAFT_ROUTINE = {
  id: ROUTINE_ID,
  tenantId: TENANT_ID,
  botId: 'bot-1',
  creatorId: USER_ID,
  title: 'Routine #1',
  description: null,
  status: 'draft',
  scheduleType: 'once',
  scheduleConfig: null,
  documentId: 'doc-flow-1',
  creationChannelId: CHANNEL_ID,
  creationSessionId: SESSION_ID,
  createdAt: new Date('2025-01-01T00:00:00.000Z'),
  updatedAt: new Date('2025-01-01T00:00:00.000Z'),
  currentExecutionId: null,
};

/** Updated routine returned from db.update().set().where().returning() after update() */
const UPDATED_ROUTINE = {
  ...DRAFT_ROUTINE,
  title: 'My Refined Routine',
  description: 'Auto-generated by creation agent',
  updatedAt: new Date('2025-01-01T01:00:00.000Z'),
};

/** Upcoming routine returned from db.update().set().where().returning() after completeCreation() */
const UPCOMING_ROUTINE = {
  ...UPDATED_ROUTINE,
  status: 'upcoming',
  updatedAt: new Date('2025-01-01T02:00:00.000Z'),
};

// ── test suite ────────────────────────────────────────────────────────

describe('Routine Creation Flow — integration', () => {
  let service: RoutinesService;
  let db: ReturnType<typeof mockDb>;
  let taskCastService: { transitionStatus: MockFn; publishEvent: MockFn };
  let amqpConnection: { publish: MockFn };
  let documentsService: { create: MockFn; update: MockFn; getById: MockFn };
  let routineTriggersService: {
    createBatch: MockFn;
    replaceAllForRoutine: MockFn;
    listByRoutine: MockFn;
  };
  let channelsService: {
    archiveCreationChannel: MockFn;
    createRoutineSessionChannel: MockFn;
    hardDeleteRoutineSessionChannel: MockFn;
  };
  let clawHiveService: {
    deleteAgent: MockFn;
    registerAgent: MockFn;
    sendInput: MockFn;
    createSession: MockFn;
    deleteSession: MockFn;
  };
  let botsService: { getBotById: MockFn };
  let wsGateway: { broadcastToWorkspace: MockFn };
  // Mocked at boundary because DB fixture seeding for `users.language` is not
  // the feature under test here. The creator returns zh-CN to verify the
  // language flows through to team9Context.language on createSession.
  let usersService: { getLocalePreferences: MockFn };
  let folder9Client: {
    createFolder: MockFn;
    createToken: MockFn;
    commit: MockFn;
    getBlob: MockFn;
  };

  beforeEach(async () => {
    db = mockDb();
    amqpConnection = { publish: jest.fn<any>().mockResolvedValue(undefined) };
    documentsService = {
      create: jest.fn<any>().mockResolvedValue({ id: 'doc-flow-1' }),
      update: jest.fn<any>().mockResolvedValue(undefined),
      getById: jest.fn<any>().mockResolvedValue({
        id: 'doc-flow-1',
        tenantId: TENANT_ID,
        currentVersion: { versionIndex: 1, content: 'some content' },
      }),
    };
    routineTriggersService = {
      createBatch: jest.fn<any>().mockResolvedValue(undefined),
      replaceAllForRoutine: jest.fn<any>().mockResolvedValue(undefined),
      listByRoutine: jest.fn<any>().mockResolvedValue([]),
    };
    taskCastService = {
      transitionStatus: jest.fn<any>().mockResolvedValue(undefined),
      publishEvent: jest.fn<any>().mockResolvedValue(undefined),
    };
    channelsService = {
      archiveCreationChannel: jest.fn<any>().mockResolvedValue(undefined),
      createRoutineSessionChannel: jest
        .fn<any>()
        .mockResolvedValue({ id: CHANNEL_ID }),
      hardDeleteRoutineSessionChannel: jest
        .fn<any>()
        .mockResolvedValue(undefined),
    };
    clawHiveService = {
      deleteAgent: jest.fn<any>().mockResolvedValue(undefined),
      registerAgent: jest.fn<any>().mockResolvedValue(undefined),
      sendInput: jest.fn<any>().mockResolvedValue({ messages: [] }),
      createSession: jest
        .fn<any>()
        .mockResolvedValue({ sessionId: SESSION_ID }),
      deleteSession: jest.fn<any>().mockResolvedValue(undefined),
    };
    botsService = {
      getBotById: jest.fn<any>().mockResolvedValue(null),
    };
    wsGateway = {
      broadcastToWorkspace: jest.fn<any>().mockResolvedValue(undefined),
    };
    usersService = {
      getLocalePreferences: jest
        .fn<any>()
        .mockResolvedValue({ language: 'zh-CN', timeZone: null }),
    };
    // Folder9ClientService — happy-path mocks for the atomic provision
    // step inside `RoutinesService.create`. The integration test exercises
    // the create → refine → complete flow under nominal conditions; failure
    // branches live in the unit spec.
    folder9Client = {
      createFolder: jest
        .fn<any>()
        .mockResolvedValue({ id: 'folder-flow-1', workspace_id: TENANT_ID }),
      createToken: jest
        .fn<any>()
        .mockResolvedValue({ token: 'tok-flow-1', expires_at: '2099-01-01' }),
      commit: jest.fn<any>().mockResolvedValue({ commit_id: 'commit-flow-1' }),
      // SKILL.md read for the A.5 validation step in completeCreation.
      // Returns a body that satisfies validateSkillMd against the
      // UPDATED_ROUTINE fixture (name slug derived from `routine-flow-1`,
      // description matches `Auto-generated by creation agent`).
      getBlob: jest.fn<any>().mockResolvedValue({
        path: 'SKILL.md',
        size: 200,
        content: [
          '---',
          'name: routine-routine-flow',
          'description: Auto-generated by creation agent',
          '---',
          '',
          'A complete routine body that easily clears the 20-char threshold.',
        ].join('\n'),
        encoding: 'text' as const,
      }),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        RoutinesService,
        { provide: DATABASE_CONNECTION, useValue: db },
        { provide: AmqpConnection, useValue: amqpConnection },
        { provide: DocumentsService, useValue: documentsService },
        { provide: RoutineTriggersService, useValue: routineTriggersService },
        { provide: TaskCastService, useValue: taskCastService },
        { provide: ChannelsService, useValue: channelsService },
        { provide: ClawHiveService, useValue: clawHiveService },
        { provide: BotService, useValue: botsService },
        { provide: WEBSOCKET_GATEWAY, useValue: wsGateway },
        { provide: UsersService, useValue: usersService },
        { provide: Folder9ClientService, useValue: folder9Client },
      ],
    }).compile();

    service = module.get<RoutinesService>(RoutinesService);
  });

  it('completes the full Routine UI path: create → refine → complete', async () => {
    // ─────────────────────────────────────────────────────────────────
    // STEP 1: createWithCreationTask
    // ─────────────────────────────────────────────────────────────────

    // Mock: getBotById → returns source bot with managedMeta.agentId
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: db.select().from().leftJoin().where().limit() — bot-tenant validation
    // The first where() call chains (returns db), then limit() resolves to result
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    // Mock: db.select().from().where() — count query (terminal, resolves directly)
    db.where.mockResolvedValueOnce([{ count: 0 }] as any);

    // Mock: documentsService.create → called by this.create() internally
    documentsService.create.mockResolvedValueOnce({ id: 'doc-flow-1' } as any);

    // Mock: db.insert().values().returning() — the draft routine row
    db.returning.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // Mock: tx.update(routines).set({folderId}).where(...) inside the
    // atomic-create transaction (A.4). The UPDATE chain consumes one
    // `db.where()` call before the trigger-block runs and before
    // startCreationSession's getRoutineOrThrow consumes its own
    // `db.where()`. We pin it here to keep the per-call mock ordering
    // stable.
    db.where.mockReturnValueOnce(db as any);

    // NOTE: previously there was an additional `db.limit.mockResolvedValueOnce([])`
    // here for the now-removed "pre-flight draft-conflict check". Drafts are
    // now allowed to coexist per (user, bot), so there is no longer a
    // SELECT between the insert and startCreationSession.

    // Mock: getRoutineOrThrow inside startCreationSession — returns the newly created draft
    // Note: no creationChannelId/creationSessionId yet (the channel hasn't been materialized)
    // db.where() for getRoutineOrThrow must return db so that db.limit() can follow.
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([
      { ...DRAFT_ROUTINE, creationChannelId: null, creationSessionId: null },
    ] as any);

    // Mock: bot-tenant re-validation inside startCreationSession
    // db.where() must return db so that db.limit() can follow.
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    // Mock: getBotById inside startCreationSession (second call; first was outer validation)
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: inline trigger fetch — db.select().from(routineTriggers).where() resolves directly
    // (routineTriggers has no tenantId column; scoped by routineId only)
    db.where.mockResolvedValueOnce([] as any);

    // Mock: channelsService.createRoutineSessionChannel
    channelsService.createRoutineSessionChannel.mockResolvedValueOnce({
      id: CHANNEL_ID,
    } as any);

    // Mock: atomic claim UPDATE — db.update().set().where().returning()
    // returning 1-row array means we won the race
    db.returning.mockResolvedValueOnce([{ id: ROUTINE_ID }] as any);

    // A.8 / C2: ensureRoutineFolder fast path — uses optimistic
    // `.limit(1)` (no row lock). Returns a row with a populated
    // folderId so no provision is invoked. Vestigial `.for('update')`
    // mock kept for any code path that still references it (none in
    // current code).
    db.for.mockResolvedValueOnce([
      { id: ROUTINE_ID, folderId: 'folder-existing' } as any,
    ]);
    db.limit.mockResolvedValueOnce([
      { id: ROUTINE_ID, folderId: 'folder-existing' } as any,
    ]);

    // Mock: clawHiveService.sendInput
    clawHiveService.sendInput.mockResolvedValueOnce({ messages: [] } as any);

    const createResult = await service.createWithCreationTask(
      { agentId: 'bot-1' },
      USER_ID,
      TENANT_ID,
    );

    // Verify the return shape — session ID uses original bot's agentId
    expect(createResult).toEqual({
      routineId: ROUTINE_ID,
      creationChannelId: CHANNEL_ID,
      creationSessionId: SESSION_ID,
    });

    // Verify routine-session channel was created with the correct params
    expect(channelsService.createRoutineSessionChannel).toHaveBeenCalledWith({
      creatorId: USER_ID,
      botUserId: SOURCE_BOT.userId,
      tenantId: TENANT_ID,
      routineId: ROUTINE_ID,
      purpose: 'creation',
    });

    // Verify NO clone agent was registered
    expect(clawHiveService.registerAgent).not.toHaveBeenCalled();

    // Verify kickoff event was sent to the original bot's session ID
    expect(clawHiveService.sendInput).toHaveBeenCalledWith(
      SESSION_ID,
      expect.objectContaining({
        type: 'team9:routine-creation.start',
        source: 'team9',
        payload: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          tenantId: TENANT_ID,
        }),
      }),
      TENANT_ID,
    );

    // ─────────────────────────────────────────────────────────────────
    // STEP 2: update (simulating agent refinement)
    // Use the routineId returned from Step 1 — this is the key cross-method
    // data flow that unit tests don't verify.
    // ─────────────────────────────────────────────────────────────────

    const { routineId } = createResult;

    // Mock: getRoutineOrThrow → draft routine (creator matches)
    db.limit.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // documentContent was dropped from UpdateRoutineDto in A.1 and the
    // permissive bridge was removed in A.4. The user-facing PATCH no
    // longer writes routine body to the linked Document — that path
    // moves to the folder9 SKILL.md proxy in A.6. So this step only
    // updates title/description/triggers.

    // Mock: routineTriggersService.replaceAllForRoutine (triggers update)
    routineTriggersService.replaceAllForRoutine.mockResolvedValueOnce(
      undefined as any,
    );

    // Mock: db.update().set().where().returning() — returns updated routine
    db.returning.mockResolvedValueOnce([UPDATED_ROUTINE] as any);

    const updateResult = await service.update(
      routineId,
      {
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        triggers: [{ type: 'manual' }],
      } as never,
      USER_ID,
      TENANT_ID,
    );

    // documentsService.update must NOT be called: the routine body update
    // flow is now folder9-backed, not document-backed.
    expect(documentsService.update).not.toHaveBeenCalled();

    // Verify triggers were replaced
    expect(routineTriggersService.replaceAllForRoutine).toHaveBeenCalledWith(
      routineId,
      [{ type: 'manual' }],
    );

    // Verify title and description were persisted
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        updatedAt: expect.any(Date),
      }),
    );

    expect(updateResult).toEqual(UPDATED_ROUTINE);

    // Verify routine:updated broadcast fired exactly once for the update
    // step, with the DB-verified tenantId and the fixture routine id.
    // replaceAllForRoutine is stubbed and must NOT emit — the outer
    // update's tail emit is the sole source of truth.
    expect(wsGateway.broadcastToWorkspace).toHaveBeenCalledTimes(1);
    expect(wsGateway.broadcastToWorkspace).toHaveBeenCalledWith(
      TENANT_ID,
      'routine:updated',
      { routineId: ROUTINE_ID },
    );

    // ─────────────────────────────────────────────────────────────────
    // STEP 3: completeCreation
    // The routineId from Step 1 is used to look up and transition the routine.
    // No clone agent exists, so no deleteAgent call. DM channel is never archived.
    // ─────────────────────────────────────────────────────────────────

    // The routine row that gets fetched here needs a folderId so
    // ensureRoutineFolder takes the fast path (otherwise it tries to
    // provision a NEW folder mid-completion, which is wrong for a
    // routine that was already fully provisioned at creation time).
    const COMPLETED_DRAFT = {
      ...UPDATED_ROUTINE,
      folderId: 'folder-flow-1',
    };

    // Mock: getRoutineOrThrow → updated draft routine with creationChannelId set
    db.limit.mockResolvedValueOnce([COMPLETED_DRAFT] as any);

    // Mock: botsService.getBotById → bot still exists (required by completeCreation validation)
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: documentsService.getById → doc with non-empty content
    documentsService.getById.mockResolvedValueOnce({
      id: DRAFT_ROUTINE.documentId,
      tenantId: TENANT_ID,
      currentVersion: {
        versionIndex: 1,
        content: 'Full task description written by agent.',
      },
    } as any);

    // C2: ensureRoutineFolder optimistic SELECT — fast path returns a
    // row with populated folderId so no provision call is made.
    // Vestigial `.for('update')` left in case any test path still
    // reaches the legacy mock.
    db.for.mockResolvedValueOnce([COMPLETED_DRAFT] as any);
    db.limit.mockResolvedValueOnce([COMPLETED_DRAFT] as any);

    // Mock: db.update().set().where().returning() → upcoming routine
    db.returning.mockResolvedValueOnce([UPCOMING_ROUTINE] as any);

    const completeResult = await service.completeCreation(
      routineId,
      { notes: 'Looks good!' },
      USER_ID,
      TENANT_ID,
    );

    // Verify status transitioned to upcoming
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({ status: 'upcoming' }),
    );

    expect(completeResult).toEqual(UPCOMING_ROUTINE);
    expect(completeResult.status).toBe('upcoming');

    // Verify creation channel was archived on completion
    expect(channelsService.archiveCreationChannel).toHaveBeenCalledWith(
      CHANNEL_ID,
      TENANT_ID,
    );

    // Verify no clone agent was deleted (there is no clone in the new architecture)
    expect(clawHiveService.deleteAgent).not.toHaveBeenCalled();

    // Verify completeCreation also broadcast routine:updated — 2 total
    // broadcasts now (one from update, one from completeCreation).
    // createWithCreationTask is a CREATE and must NOT broadcast, so the
    // count stays at 2.
    expect(wsGateway.broadcastToWorkspace).toHaveBeenCalledTimes(2);
    expect(wsGateway.broadcastToWorkspace).toHaveBeenNthCalledWith(
      2,
      TENANT_ID,
      'routine:updated',
      { routineId: ROUTINE_ID },
    );
  });

  it('materializes a routine-session channel for an existing draft via startCreationSession', async () => {
    // Mock getRoutineOrThrow → a draft with creationChannelId=null (onboarding-provisioned style)
    const draftWithoutChannel = {
      ...DRAFT_ROUTINE,
      creationChannelId: null,
      creationSessionId: null,
    };
    // Three db.where() calls before the atomic claim in startCreationSession:
    //   #1 getRoutineOrThrow, #2 bot-tenant re-validation, #3 trigger fetch
    // #1: getRoutineOrThrow needs where() to return db so .limit() can follow
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([draftWithoutChannel] as any);

    // #2: Bot-tenant re-validation (new in Round 1 fix #3)
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock documentsService.getById to return null content (no draft document enrichment)
    documentsService.getById.mockResolvedValueOnce({
      id: 'doc-flow-1',
      tenantId: TENANT_ID,
      currentVersion: null,
    } as any);

    // #3: Inline trigger fetch — db.select().from(routineTriggers).where() resolves directly
    db.where.mockResolvedValueOnce([] as any);

    channelsService.createRoutineSessionChannel.mockResolvedValueOnce({
      id: CHANNEL_ID,
    } as any);

    // Atomic claim UPDATE returning 1 row = won the race
    db.returning.mockResolvedValueOnce([{ id: ROUTINE_ID }] as any);

    // A.8 / C2: ensureRoutineFolder fast path (optimistic .limit(1))
    db.for.mockResolvedValueOnce([
      { id: ROUTINE_ID, folderId: 'folder-existing' } as any,
    ]);
    db.limit.mockResolvedValueOnce([
      { id: ROUTINE_ID, folderId: 'folder-existing' } as any,
    ]);

    clawHiveService.sendInput.mockResolvedValueOnce({ messages: [] } as any);

    const result = await service.startCreationSession(
      ROUTINE_ID,
      USER_ID,
      TENANT_ID,
    );

    expect(result).toEqual({
      creationChannelId: CHANNEL_ID,
      creationSessionId: SESSION_ID,
    });

    expect(channelsService.createRoutineSessionChannel).toHaveBeenCalledWith({
      creatorId: USER_ID,
      botUserId: SOURCE_BOT.userId,
      tenantId: TENANT_ID,
      routineId: ROUTINE_ID,
      purpose: 'creation',
    });

    // Assert createSession was called with team9Context.routineId + isCreationChannel: true.
    // Note: the spec's "team9Context.routineId reaches the agent" goal is verified
    // here at the createSession call boundary (Hive client mock). Verifying the
    // agent's downstream config propagation (i.e., the rendered kickoff conversation
    // entry) requires a live agent-pi runtime, which is out of scope for this
    // mock-based integration test. The agent-pi side has its own unit tests in
    // `Team9RoutineCreationComponent.formatEventEntry` covering payload-to-entry
    // rendering.
    expect(clawHiveService.createSession).toHaveBeenCalledWith(
      AGENT_ID,
      expect.objectContaining({
        userId: USER_ID,
        sessionId: SESSION_ID,
        team9Context: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          creationChannelId: CHANNEL_ID,
          isCreationChannel: true,
          language: 'zh-CN',
        }),
      }),
      TENANT_ID,
    );

    expect(clawHiveService.sendInput).toHaveBeenCalledWith(
      SESSION_ID,
      expect.objectContaining({
        type: 'team9:routine-creation.start',
        payload: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          tenantId: TENANT_ID,
          creationChannelId: CHANNEL_ID,
          title: DRAFT_ROUTINE.title,
          description: null,
          documentContent: null,
          botId: DRAFT_ROUTINE.botId,
          triggers: [],
        }),
      }),
      TENANT_ID,
    );
  });

  it('hard-deletes the creation channel when deleting a draft', async () => {
    // Mock getRoutineOrThrow → a draft with creationChannelId set
    db.limit.mockResolvedValueOnce([
      {
        ...DRAFT_ROUTINE,
        creationChannelId: CHANNEL_ID,
      },
    ] as any);

    await service.delete(ROUTINE_ID, USER_ID, TENANT_ID);

    expect(
      channelsService.hardDeleteRoutineSessionChannel,
    ).toHaveBeenCalledWith(CHANNEL_ID, TENANT_ID);
    expect(db.delete).toHaveBeenCalled();
    // A-I9: delete also broadcasts routine:updated so clients refetch.
    expect(wsGateway.broadcastToWorkspace).toHaveBeenCalledWith(
      TENANT_ID,
      'routine:updated',
      { routineId: ROUTINE_ID },
    );
  });
});
