/**
 * End-to-end integration test for the Routine creation flow.
 *
 * Exercises the full Routine UI path in sequence:
 *   1. createWithCreationTask — creates draft routine + DM channel + clone agent
 *   2. update — simulates agent refinement (title, documentContent, triggers)
 *   3. completeCreation — transitions to upcoming, archives channel, deletes clone
 *
 * This is a mock-based test (no real DB). The key thing it verifies that
 * individual unit tests don't: the routineId returned from createWithCreationTask
 * flows correctly into update and completeCreation, and the clone agent ID
 * (`routine-creation-<routineId>`) is consistent across create and complete.
 */

import { jest, describe, it, expect, beforeEach } from '@jest/globals';
import { Test, TestingModule } from '@nestjs/testing';
import { RoutinesService } from '../routines.service.js';
import { TaskCastService } from '../taskcast.service.js';
import { DATABASE_CONNECTION } from '@team9/database';
import { DocumentsService } from '../../documents/documents.service.js';
import { ChannelsService } from '../../im/channels/channels.service.js';
import { ClawHiveService } from '@team9/claw-hive';
import { BotService } from '../../bot/bot.service.js';
import { RoutineTriggersService } from '../routine-triggers.service.js';
import { AmqpConnection } from '@team9/rabbitmq';

// ── helpers ──────────────────────────────────────────────────────────

type MockFn = jest.Mock<(...args: any[]) => any>;

function mockDb() {
  const chain: Record<string, MockFn> = {};
  const methods = [
    'select',
    'from',
    'where',
    'limit',
    'insert',
    'values',
    'returning',
    'update',
    'set',
    'and',
    'orderBy',
    'desc',
    'delete',
    'leftJoin',
    'innerJoin',
  ];
  for (const m of methods) {
    chain[m] = jest.fn<any>().mockReturnValue(chain);
  }
  chain.limit.mockResolvedValue([]);
  chain.returning.mockResolvedValue([]);
  return chain;
}

// ── fixtures ─────────────────────────────────────────────────────────

const ROUTINE_ID = 'routine-flow-1';
const TENANT_ID = 'tenant-1';
const USER_ID = 'user-1';
const CHANNEL_ID = 'channel-flow-1';
const SESSION_ID = `team9/${TENANT_ID}/routine-creation-${ROUTINE_ID}/dm/${CHANNEL_ID}`;
const CLONE_AGENT_ID = `routine-creation-${ROUTINE_ID}`;

const SOURCE_BOT = {
  userId: 'bot-user-1',
  botId: 'bot-1',
  username: 'my-bot',
  displayName: 'My Bot',
  email: 'bot@team9.local',
  type: 'custom',
  ownerId: 'owner-1',
  mentorId: null,
  description: null,
  capabilities: null,
  extra: null,
  managedProvider: 'hive',
  managedMeta: { agentId: 'source-agent-id' },
  isActive: true,
};

const SOURCE_AGENT = {
  id: 'source-agent-id',
  name: 'My Bot Agent',
  blueprintId: 'blueprint-abc',
  tenantId: TENANT_ID,
  model: { provider: 'openrouter', id: 'anthropic/claude-sonnet-4' },
  componentConfigs: { 'system-prompt': { prompt: 'You are helpful.' } },
};

/** Draft routine returned from db.insert().values().returning() */
const DRAFT_ROUTINE = {
  id: ROUTINE_ID,
  tenantId: TENANT_ID,
  botId: 'bot-1',
  creatorId: USER_ID,
  title: 'Routine #1',
  description: null,
  status: 'draft',
  scheduleType: 'once',
  scheduleConfig: null,
  documentId: 'doc-flow-1',
  creationChannelId: CHANNEL_ID,
  creationSessionId: SESSION_ID,
  createdAt: new Date('2025-01-01T00:00:00.000Z'),
  updatedAt: new Date('2025-01-01T00:00:00.000Z'),
  currentExecutionId: null,
};

/** Updated routine returned from db.update().set().where().returning() after update() */
const UPDATED_ROUTINE = {
  ...DRAFT_ROUTINE,
  title: 'My Refined Routine',
  description: 'Auto-generated by creation agent',
  updatedAt: new Date('2025-01-01T01:00:00.000Z'),
};

/** Upcoming routine returned from db.update().set().where().returning() after completeCreation() */
const UPCOMING_ROUTINE = {
  ...UPDATED_ROUTINE,
  status: 'upcoming',
  updatedAt: new Date('2025-01-01T02:00:00.000Z'),
};

// ── test suite ────────────────────────────────────────────────────────

describe('Routine Creation Flow — integration', () => {
  let service: RoutinesService;
  let db: ReturnType<typeof mockDb>;
  let taskCastService: { transitionStatus: MockFn; publishEvent: MockFn };
  let amqpConnection: { publish: MockFn };
  let documentsService: { create: MockFn; update: MockFn; getById: MockFn };
  let routineTriggersService: { createBatch: MockFn; replaceAllForRoutine: MockFn };
  let channelsService: { archiveCreationChannel: MockFn; createDirectChannel: MockFn };
  let clawHiveService: {
    deleteAgent: MockFn;
    registerAgent: MockFn;
    sendInput: MockFn;
    getAgent: MockFn;
  };
  let botsService: { getBotById: MockFn };

  beforeEach(async () => {
    db = mockDb();
    amqpConnection = { publish: jest.fn<any>().mockResolvedValue(undefined) };
    documentsService = {
      create: jest.fn<any>().mockResolvedValue({ id: 'doc-flow-1' }),
      update: jest.fn<any>().mockResolvedValue(undefined),
      getById: jest.fn<any>().mockResolvedValue({ id: 'doc-flow-1', content: 'some content' }),
    };
    routineTriggersService = {
      createBatch: jest.fn<any>().mockResolvedValue(undefined),
      replaceAllForRoutine: jest.fn<any>().mockResolvedValue(undefined),
    };
    taskCastService = {
      transitionStatus: jest.fn<any>().mockResolvedValue(undefined),
      publishEvent: jest.fn<any>().mockResolvedValue(undefined),
    };
    channelsService = {
      archiveCreationChannel: jest.fn<any>().mockResolvedValue(undefined),
      createDirectChannel: jest.fn<any>().mockResolvedValue({ id: CHANNEL_ID }),
    };
    clawHiveService = {
      deleteAgent: jest.fn<any>().mockResolvedValue(undefined),
      registerAgent: jest.fn<any>().mockResolvedValue(undefined),
      sendInput: jest.fn<any>().mockResolvedValue({ messages: [] }),
      getAgent: jest.fn<any>().mockResolvedValue(null),
    };
    botsService = {
      getBotById: jest.fn<any>().mockResolvedValue(null),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        RoutinesService,
        { provide: DATABASE_CONNECTION, useValue: db },
        { provide: AmqpConnection, useValue: amqpConnection },
        { provide: DocumentsService, useValue: documentsService },
        { provide: RoutineTriggersService, useValue: routineTriggersService },
        { provide: TaskCastService, useValue: taskCastService },
        { provide: ChannelsService, useValue: channelsService },
        { provide: ClawHiveService, useValue: clawHiveService },
        { provide: BotService, useValue: botsService },
      ],
    }).compile();

    service = module.get<RoutinesService>(RoutinesService);
  });

  it('completes the full Routine UI path: create → refine → complete', async () => {
    // ─────────────────────────────────────────────────────────────────
    // STEP 1: createWithCreationTask
    // ─────────────────────────────────────────────────────────────────

    // Mock: getBotById → returns source bot with managedMeta.agentId
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: db.select().from().leftJoin().where().limit() — bot-tenant validation
    // The first where() call chains (returns db), then limit() resolves to result
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    // Mock: db.select().from().where() — count query (terminal, resolves directly)
    db.where.mockResolvedValueOnce([{ count: 0 }] as any);

    // Mock: clawHiveService.getAgent → returns source agent
    (clawHiveService as any).getAgent.mockResolvedValueOnce(SOURCE_AGENT);

    // Mock: documentsService.create → called by this.create() internally
    documentsService.create.mockResolvedValueOnce({ id: 'doc-flow-1' } as any);

    // Mock: db.insert().values().returning() — the draft routine row
    db.returning.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // Mock: channelsService.createDirectChannel
    channelsService.createDirectChannel.mockResolvedValueOnce({ id: CHANNEL_ID } as any);

    // Mock: clawHiveService.registerAgent (no return value needed)
    clawHiveService.registerAgent.mockResolvedValueOnce(undefined as any);

    // Mock: db.update().set().where() — persist creationChannelId + creationSessionId
    // (no .returning() called in step 9 of createWithCreationTask)
    // The chain already returns chain by default; no special mock needed.

    // Mock: clawHiveService.sendInput
    clawHiveService.sendInput.mockResolvedValueOnce({ messages: [] } as any);

    const createResult = await service.createWithCreationTask(
      { agentId: 'bot-1' },
      USER_ID,
      TENANT_ID,
    );

    // Verify the return shape
    expect(createResult).toEqual({
      routineId: ROUTINE_ID,
      creationChannelId: CHANNEL_ID,
      creationSessionId: SESSION_ID,
    });

    // Verify DM channel was created for the right user + bot shadow user
    expect(channelsService.createDirectChannel).toHaveBeenCalledWith(
      USER_ID,
      SOURCE_BOT.userId,
      TENANT_ID,
    );

    // Verify clone agent was registered with deterministic ID and correct config
    expect(clawHiveService.registerAgent).toHaveBeenCalledWith(
      expect.objectContaining({
        id: CLONE_AGENT_ID,
        blueprintId: SOURCE_AGENT.blueprintId,
        tenantId: TENANT_ID,
        model: SOURCE_AGENT.model,
        componentConfigs: expect.objectContaining({
          'system-prompt': SOURCE_AGENT.componentConfigs['system-prompt'],
          'team9-routine-creation': {
            routineId: ROUTINE_ID,
            isCreationChannel: true,
          },
        }),
      }),
    );

    // Verify kickoff event was sent with the correct session ID and payload
    expect(clawHiveService.sendInput).toHaveBeenCalledWith(
      SESSION_ID,
      expect.objectContaining({
        type: 'team9:routine-creation.start',
        source: 'team9',
        payload: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          tenantId: TENANT_ID,
        }),
      }),
      TENANT_ID,
    );

    // ─────────────────────────────────────────────────────────────────
    // STEP 2: update (simulating agent refinement)
    // Use the routineId returned from Step 1 — this is the key cross-method
    // data flow that unit tests don't verify.
    // ─────────────────────────────────────────────────────────────────

    const { routineId } = createResult;

    // Mock: getRoutineOrThrow → draft routine (creator matches)
    db.limit.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // Mock: documentsService.update (documentContent update)
    documentsService.update.mockResolvedValueOnce(undefined as any);

    // Mock: routineTriggersService.replaceAllForRoutine (triggers update)
    routineTriggersService.replaceAllForRoutine.mockResolvedValueOnce(undefined as any);

    // Mock: db.update().set().where().returning() — returns updated routine
    db.returning.mockResolvedValueOnce([UPDATED_ROUTINE] as any);

    const updateResult = await service.update(
      routineId,
      {
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        documentContent: 'Full task description written by agent.',
        triggers: [{ type: 'manual' }],
      } as never,
      USER_ID,
      TENANT_ID,
    );

    // Verify documentContent was written to the linked document
    expect(documentsService.update).toHaveBeenCalledWith(
      DRAFT_ROUTINE.documentId,
      { content: 'Full task description written by agent.' },
      { type: 'user', id: USER_ID },
    );

    // Verify triggers were replaced
    expect(routineTriggersService.replaceAllForRoutine).toHaveBeenCalledWith(
      routineId,
      [{ type: 'manual' }],
      TENANT_ID,
    );

    // Verify title and description were persisted
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        updatedAt: expect.any(Date),
      }),
    );

    expect(updateResult).toEqual(UPDATED_ROUTINE);

    // ─────────────────────────────────────────────────────────────────
    // STEP 3: completeCreation
    // The routineId from Step 1 is used, and the clone agent ID
    // (`routine-creation-<routineId>`) must match what was registered in Step 1.
    // ─────────────────────────────────────────────────────────────────

    // Mock: getRoutineOrThrow → updated draft routine with creationChannelId set
    db.limit.mockResolvedValueOnce([UPDATED_ROUTINE] as any);

    // Mock: botsService.getBotById → bot still exists (required by completeCreation validation)
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: documentsService.getById → doc with non-empty content
    documentsService.getById.mockResolvedValueOnce({
      id: DRAFT_ROUTINE.documentId,
      content: 'Full task description written by agent.',
    } as any);

    // Mock: db.update().set().where().returning() → upcoming routine
    db.returning.mockResolvedValueOnce([UPCOMING_ROUTINE] as any);

    // Mock: channelsService.archiveCreationChannel
    channelsService.archiveCreationChannel.mockResolvedValueOnce(undefined as any);

    // Mock: clawHiveService.deleteAgent
    clawHiveService.deleteAgent.mockResolvedValueOnce(undefined as any);

    const completeResult = await service.completeCreation(
      routineId,
      { notes: 'Looks good!' },
      USER_ID,
      TENANT_ID,
    );

    // Verify status transitioned to upcoming
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({ status: 'upcoming' }),
    );

    expect(completeResult).toEqual(UPCOMING_ROUTINE);
    expect(completeResult.status).toBe('upcoming');

    // Verify creation channel was archived using the channel ID from Step 1
    expect(channelsService.archiveCreationChannel).toHaveBeenCalledWith(
      CHANNEL_ID,
      TENANT_ID,
    );

    // Verify clone agent was deleted using the SAME ID that was registered in Step 1.
    // This is the cross-step consistency check: `routine-creation-<routineId>`
    // must be identical in both registerAgent (Step 1) and deleteAgent (Step 3).
    expect(clawHiveService.deleteAgent).toHaveBeenCalledWith(CLONE_AGENT_ID);
    expect(CLONE_AGENT_ID).toBe(`routine-creation-${routineId}`);
  });
});
