/**
 * End-to-end integration test for the Routine creation flow.
 *
 * Exercises the full Routine UI path in sequence:
 *   1. createWithCreationTask — creates draft routine + routine-session channel,
 *      sends kickoff to the ORIGINAL bot's session (no clone agent)
 *   2. update — simulates agent refinement (title, documentContent, triggers)
 *   3. completeCreation — transitions to upcoming, archives the creation channel
 *
 * This is a mock-based test (no real DB). The key thing it verifies that
 * individual unit tests don't: the routineId returned from createWithCreationTask
 * flows correctly into update and completeCreation, and the session ID uses the
 * original bot's agentId (matching what post-broadcast derives).
 */

import { jest, describe, it, expect, beforeEach } from '@jest/globals';
import { Test, TestingModule } from '@nestjs/testing';
import { RoutinesService } from '../routines.service.js';
import { TaskCastService } from '../taskcast.service.js';
import { DATABASE_CONNECTION } from '@team9/database';
import { DocumentsService } from '../../documents/documents.service.js';
import { ChannelsService } from '../../im/channels/channels.service.js';
import { ClawHiveService } from '@team9/claw-hive';
import { BotService } from '../../bot/bot.service.js';
import { RoutineTriggersService } from '../routine-triggers.service.js';
import { AmqpConnection } from '@team9/rabbitmq';

// ── helpers ──────────────────────────────────────────────────────────

type MockFn = jest.Mock<(...args: any[]) => any>;

function mockDb() {
  const chain: Record<string, MockFn> = {};
  const methods = [
    'select',
    'from',
    'where',
    'limit',
    'insert',
    'values',
    'returning',
    'update',
    'set',
    'and',
    'orderBy',
    'desc',
    'delete',
    'leftJoin',
    'innerJoin',
  ];
  for (const m of methods) {
    chain[m] = jest.fn<any>().mockReturnValue(chain);
  }
  chain.limit.mockResolvedValue([]);
  chain.returning.mockResolvedValue([]);
  return chain;
}

// ── fixtures ─────────────────────────────────────────────────────────

const ROUTINE_ID = 'routine-flow-1';
const TENANT_ID = 'tenant-1';
const USER_ID = 'user-1';
const CHANNEL_ID = 'channel-flow-1';
const AGENT_ID = 'source-agent-id';
// Session ID uses the original bot's agentId (not a clone)
const SESSION_ID = `team9/${TENANT_ID}/${AGENT_ID}/dm/${CHANNEL_ID}`;

const SOURCE_BOT = {
  userId: 'bot-user-1',
  botId: 'bot-1',
  username: 'my-bot',
  displayName: 'My Bot',
  email: 'bot@team9.local',
  type: 'custom',
  ownerId: 'owner-1',
  mentorId: null,
  description: null,
  capabilities: null,
  extra: null,
  managedProvider: 'hive',
  managedMeta: { agentId: AGENT_ID },
  isActive: true,
};

/** Draft routine returned from db.insert().values().returning() */
const DRAFT_ROUTINE = {
  id: ROUTINE_ID,
  tenantId: TENANT_ID,
  botId: 'bot-1',
  creatorId: USER_ID,
  title: 'Routine #1',
  description: null,
  status: 'draft',
  scheduleType: 'once',
  scheduleConfig: null,
  documentId: 'doc-flow-1',
  creationChannelId: CHANNEL_ID,
  creationSessionId: SESSION_ID,
  createdAt: new Date('2025-01-01T00:00:00.000Z'),
  updatedAt: new Date('2025-01-01T00:00:00.000Z'),
  currentExecutionId: null,
};

/** Updated routine returned from db.update().set().where().returning() after update() */
const UPDATED_ROUTINE = {
  ...DRAFT_ROUTINE,
  title: 'My Refined Routine',
  description: 'Auto-generated by creation agent',
  updatedAt: new Date('2025-01-01T01:00:00.000Z'),
};

/** Upcoming routine returned from db.update().set().where().returning() after completeCreation() */
const UPCOMING_ROUTINE = {
  ...UPDATED_ROUTINE,
  status: 'upcoming',
  updatedAt: new Date('2025-01-01T02:00:00.000Z'),
};

// ── test suite ────────────────────────────────────────────────────────

describe('Routine Creation Flow — integration', () => {
  let service: RoutinesService;
  let db: ReturnType<typeof mockDb>;
  let taskCastService: { transitionStatus: MockFn; publishEvent: MockFn };
  let amqpConnection: { publish: MockFn };
  let documentsService: { create: MockFn; update: MockFn; getById: MockFn };
  let routineTriggersService: {
    createBatch: MockFn;
    replaceAllForRoutine: MockFn;
  };
  let channelsService: {
    archiveCreationChannel: MockFn;
    createRoutineSessionChannel: MockFn;
    hardDeleteRoutineSessionChannel: MockFn;
  };
  let clawHiveService: {
    deleteAgent: MockFn;
    registerAgent: MockFn;
    sendInput: MockFn;
    createSession: MockFn;
    deleteSession: MockFn;
  };
  let botsService: { getBotById: MockFn };

  beforeEach(async () => {
    db = mockDb();
    amqpConnection = { publish: jest.fn<any>().mockResolvedValue(undefined) };
    documentsService = {
      create: jest.fn<any>().mockResolvedValue({ id: 'doc-flow-1' }),
      update: jest.fn<any>().mockResolvedValue(undefined),
      getById: jest
        .fn<any>()
        .mockResolvedValue({ id: 'doc-flow-1', content: 'some content' }),
    };
    routineTriggersService = {
      createBatch: jest.fn<any>().mockResolvedValue(undefined),
      replaceAllForRoutine: jest.fn<any>().mockResolvedValue(undefined),
    };
    taskCastService = {
      transitionStatus: jest.fn<any>().mockResolvedValue(undefined),
      publishEvent: jest.fn<any>().mockResolvedValue(undefined),
    };
    channelsService = {
      archiveCreationChannel: jest.fn<any>().mockResolvedValue(undefined),
      createRoutineSessionChannel: jest
        .fn<any>()
        .mockResolvedValue({ id: CHANNEL_ID }),
      hardDeleteRoutineSessionChannel: jest
        .fn<any>()
        .mockResolvedValue(undefined),
    };
    clawHiveService = {
      deleteAgent: jest.fn<any>().mockResolvedValue(undefined),
      registerAgent: jest.fn<any>().mockResolvedValue(undefined),
      sendInput: jest.fn<any>().mockResolvedValue({ messages: [] }),
      createSession: jest
        .fn<any>()
        .mockResolvedValue({ sessionId: SESSION_ID }),
      deleteSession: jest.fn<any>().mockResolvedValue(undefined),
    };
    botsService = {
      getBotById: jest.fn<any>().mockResolvedValue(null),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        RoutinesService,
        { provide: DATABASE_CONNECTION, useValue: db },
        { provide: AmqpConnection, useValue: amqpConnection },
        { provide: DocumentsService, useValue: documentsService },
        { provide: RoutineTriggersService, useValue: routineTriggersService },
        { provide: TaskCastService, useValue: taskCastService },
        { provide: ChannelsService, useValue: channelsService },
        { provide: ClawHiveService, useValue: clawHiveService },
        { provide: BotService, useValue: botsService },
      ],
    }).compile();

    service = module.get<RoutinesService>(RoutinesService);
  });

  it('completes the full Routine UI path: create → refine → complete', async () => {
    // ─────────────────────────────────────────────────────────────────
    // STEP 1: createWithCreationTask
    // ─────────────────────────────────────────────────────────────────

    // Mock: getBotById → returns source bot with managedMeta.agentId
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: db.select().from().leftJoin().where().limit() — bot-tenant validation
    // The first where() call chains (returns db), then limit() resolves to result
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    // Mock: db.select().from().where() — count query (terminal, resolves directly)
    db.where.mockResolvedValueOnce([{ count: 0 }] as any);

    // Mock: documentsService.create → called by this.create() internally
    documentsService.create.mockResolvedValueOnce({ id: 'doc-flow-1' } as any);

    // Mock: db.insert().values().returning() — the draft routine row
    db.returning.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // NOTE: previously there was an additional `db.limit.mockResolvedValueOnce([])`
    // here for the now-removed "pre-flight draft-conflict check". Drafts are
    // now allowed to coexist per (user, bot), so there is no longer a
    // SELECT between the insert and startCreationSession.

    // Mock: getRoutineOrThrow inside startCreationSession — returns the newly created draft
    // Note: no creationChannelId/creationSessionId yet (the channel hasn't been materialized)
    db.limit.mockResolvedValueOnce([
      { ...DRAFT_ROUTINE, creationChannelId: null, creationSessionId: null },
    ] as any);

    // Mock: bot-tenant re-validation inside startCreationSession
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    // Mock: getBotById inside startCreationSession (second call; first was outer validation)
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: channelsService.createRoutineSessionChannel
    channelsService.createRoutineSessionChannel.mockResolvedValueOnce({
      id: CHANNEL_ID,
    } as any);

    // Mock: atomic claim UPDATE — db.update().set().where().returning()
    // returning 1-row array means we won the race
    db.returning.mockResolvedValueOnce([{ id: ROUTINE_ID }] as any);

    // Mock: clawHiveService.sendInput
    clawHiveService.sendInput.mockResolvedValueOnce({ messages: [] } as any);

    const createResult = await service.createWithCreationTask(
      { agentId: 'bot-1' },
      USER_ID,
      TENANT_ID,
    );

    // Verify the return shape — session ID uses original bot's agentId
    expect(createResult).toEqual({
      routineId: ROUTINE_ID,
      creationChannelId: CHANNEL_ID,
      creationSessionId: SESSION_ID,
    });

    // Verify routine-session channel was created with the correct params
    expect(channelsService.createRoutineSessionChannel).toHaveBeenCalledWith({
      creatorId: USER_ID,
      botUserId: SOURCE_BOT.userId,
      tenantId: TENANT_ID,
      routineId: ROUTINE_ID,
      purpose: 'creation',
    });

    // Verify NO clone agent was registered
    expect(clawHiveService.registerAgent).not.toHaveBeenCalled();

    // Verify kickoff event was sent to the original bot's session ID
    expect(clawHiveService.sendInput).toHaveBeenCalledWith(
      SESSION_ID,
      expect.objectContaining({
        type: 'team9:routine-creation.start',
        source: 'team9',
        payload: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          tenantId: TENANT_ID,
        }),
      }),
      TENANT_ID,
    );

    // ─────────────────────────────────────────────────────────────────
    // STEP 2: update (simulating agent refinement)
    // Use the routineId returned from Step 1 — this is the key cross-method
    // data flow that unit tests don't verify.
    // ─────────────────────────────────────────────────────────────────

    const { routineId } = createResult;

    // Mock: getRoutineOrThrow → draft routine (creator matches)
    db.limit.mockResolvedValueOnce([DRAFT_ROUTINE] as any);

    // Mock: documentsService.update (documentContent update)
    documentsService.update.mockResolvedValueOnce(undefined as any);

    // Mock: routineTriggersService.replaceAllForRoutine (triggers update)
    routineTriggersService.replaceAllForRoutine.mockResolvedValueOnce(
      undefined as any,
    );

    // Mock: db.update().set().where().returning() — returns updated routine
    db.returning.mockResolvedValueOnce([UPDATED_ROUTINE] as any);

    const updateResult = await service.update(
      routineId,
      {
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        documentContent: 'Full task description written by agent.',
        triggers: [{ type: 'manual' }],
      } as never,
      USER_ID,
      TENANT_ID,
    );

    // Verify documentContent was written to the linked document
    expect(documentsService.update).toHaveBeenCalledWith(
      DRAFT_ROUTINE.documentId,
      { content: 'Full task description written by agent.' },
      { type: 'user', id: USER_ID },
    );

    // Verify triggers were replaced
    expect(routineTriggersService.replaceAllForRoutine).toHaveBeenCalledWith(
      routineId,
      [{ type: 'manual' }],
    );

    // Verify title and description were persisted
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({
        title: 'My Refined Routine',
        description: 'Auto-generated by creation agent',
        updatedAt: expect.any(Date),
      }),
    );

    expect(updateResult).toEqual(UPDATED_ROUTINE);

    // ─────────────────────────────────────────────────────────────────
    // STEP 3: completeCreation
    // The routineId from Step 1 is used to look up and transition the routine.
    // No clone agent exists, so no deleteAgent call. DM channel is never archived.
    // ─────────────────────────────────────────────────────────────────

    // Mock: getRoutineOrThrow → updated draft routine with creationChannelId set
    db.limit.mockResolvedValueOnce([UPDATED_ROUTINE] as any);

    // Mock: botsService.getBotById → bot still exists (required by completeCreation validation)
    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock: documentsService.getById → doc with non-empty content
    documentsService.getById.mockResolvedValueOnce({
      id: DRAFT_ROUTINE.documentId,
      content: 'Full task description written by agent.',
    } as any);

    // Mock: db.update().set().where().returning() → upcoming routine
    db.returning.mockResolvedValueOnce([UPCOMING_ROUTINE] as any);

    const completeResult = await service.completeCreation(
      routineId,
      { notes: 'Looks good!' },
      USER_ID,
      TENANT_ID,
    );

    // Verify status transitioned to upcoming
    expect(db.set).toHaveBeenCalledWith(
      expect.objectContaining({ status: 'upcoming' }),
    );

    expect(completeResult).toEqual(UPCOMING_ROUTINE);
    expect(completeResult.status).toBe('upcoming');

    // Verify creation channel was archived on completion
    expect(channelsService.archiveCreationChannel).toHaveBeenCalledWith(
      CHANNEL_ID,
      TENANT_ID,
    );

    // Verify no clone agent was deleted (there is no clone in the new architecture)
    expect(clawHiveService.deleteAgent).not.toHaveBeenCalled();
  });

  it('materializes a routine-session channel for an existing draft via startCreationSession', async () => {
    // Mock getRoutineOrThrow → a draft with creationChannelId=null (onboarding-provisioned style)
    const draftWithoutChannel = {
      ...DRAFT_ROUTINE,
      creationChannelId: null,
      creationSessionId: null,
    };
    db.limit.mockResolvedValueOnce([draftWithoutChannel] as any);

    // Bot-tenant re-validation (new in Round 1 fix #3)
    db.where.mockReturnValueOnce(db as any);
    db.limit.mockResolvedValueOnce([{ tenantId: TENANT_ID }] as any);

    botsService.getBotById.mockResolvedValueOnce(SOURCE_BOT as any);

    // Mock documentsService.getById to return null content (no draft document enrichment)
    documentsService.getById.mockResolvedValueOnce({
      id: 'doc-flow-1',
      content: null,
    } as any);

    channelsService.createRoutineSessionChannel.mockResolvedValueOnce({
      id: CHANNEL_ID,
    } as any);

    // Atomic claim UPDATE returning 1 row = won the race
    db.returning.mockResolvedValueOnce([{ id: ROUTINE_ID }] as any);

    clawHiveService.sendInput.mockResolvedValueOnce({ messages: [] } as any);

    const result = await service.startCreationSession(
      ROUTINE_ID,
      USER_ID,
      TENANT_ID,
    );

    expect(result).toEqual({
      creationChannelId: CHANNEL_ID,
      creationSessionId: SESSION_ID,
    });

    expect(channelsService.createRoutineSessionChannel).toHaveBeenCalledWith({
      creatorId: USER_ID,
      botUserId: SOURCE_BOT.userId,
      tenantId: TENANT_ID,
      routineId: ROUTINE_ID,
      purpose: 'creation',
    });

    // Assert createSession was called with team9Context.routineId + isCreationChannel: true.
    // Note: the spec's "team9Context.routineId reaches the agent" goal is verified
    // here at the createSession call boundary (Hive client mock). Verifying the
    // agent's downstream config propagation (i.e., the rendered kickoff conversation
    // entry) requires a live agent-pi runtime, which is out of scope for this
    // mock-based integration test. The agent-pi side has its own unit tests in
    // `Team9RoutineCreationComponent.formatEventEntry` covering payload-to-entry
    // rendering.
    expect(clawHiveService.createSession).toHaveBeenCalledWith(
      AGENT_ID,
      expect.objectContaining({
        userId: USER_ID,
        sessionId: SESSION_ID,
        team9Context: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          creationChannelId: CHANNEL_ID,
          isCreationChannel: true,
        }),
      }),
      TENANT_ID,
    );

    expect(clawHiveService.sendInput).toHaveBeenCalledWith(
      SESSION_ID,
      expect.objectContaining({
        type: 'team9:routine-creation.start',
        payload: expect.objectContaining({
          routineId: ROUTINE_ID,
          creatorUserId: USER_ID,
          tenantId: TENANT_ID,
          creationChannelId: CHANNEL_ID,
          title: DRAFT_ROUTINE.title,
          description: null,
          documentContent: null,
          botId: DRAFT_ROUTINE.botId,
          triggers: [],
        }),
      }),
      TENANT_ID,
    );
  });

  it('hard-deletes the creation channel when deleting a draft', async () => {
    // Mock getRoutineOrThrow → a draft with creationChannelId set
    db.limit.mockResolvedValueOnce([
      {
        ...DRAFT_ROUTINE,
        creationChannelId: CHANNEL_ID,
      },
    ] as any);

    await service.delete(ROUTINE_ID, USER_ID, TENANT_ID);

    expect(
      channelsService.hardDeleteRoutineSessionChannel,
    ).toHaveBeenCalledWith(CHANNEL_ID, TENANT_ID);
    expect(db.delete).toHaveBeenCalled();
  });
});
