# Root workspace - manages shared development tooling
# Each app (client, server) has its own workspace for independent builds
packages:
  - "apps/*"
  - "apps/server/apps/*"
  - "apps/server/libs/*"
  # Enterprise modules (optional - loaded via git submodule)
  - "enterprise/libs/*"
