import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { Building2, AlertCircle } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCreateWorkspace } from "@/hooks/useWorkspace";
import { useWorkspaceStore } from "@/stores";

interface CreateWorkspaceDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * Generate a preview slug from the name (for display only).
 * The actual slug is generated by the backend.
 */
function generateSlugPreview(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .substring(0, 50);
}

function validateWorkspaceName(name: string): {
  valid: boolean;
  error?: string;
} {
  if (!name || name.trim().length === 0) {
    return { valid: false, error: "Workspace name is required" };
  }
  if (name.trim().length < 2) {
    return { valid: false, error: "Name must be at least 2 characters" };
  }
  if (name.length > 100) {
    return { valid: false, error: "Name must be 100 characters or less" };
  }
  return { valid: true };
}

export function CreateWorkspaceDialog({
  isOpen,
  onClose,
}: CreateWorkspaceDialogProps) {
  const { t } = useTranslation("workspace");
  const createWorkspace = useCreateWorkspace();
  const { setSelectedWorkspaceId } = useWorkspaceStore();

  const [name, setName] = useState("");
  const [slugPreview, setSlugPreview] = useState("");
  const [nameError, setNameError] = useState<string | null>(null);
  const [apiError, setApiError] = useState<string | null>(null);

  // Generate slug preview from name
  useEffect(() => {
    setSlugPreview(generateSlugPreview(name));
  }, [name]);

  // Validate name
  useEffect(() => {
    if (name) {
      const validation = validateWorkspaceName(name);
      setNameError(validation.valid ? null : validation.error || null);
    } else {
      setNameError(null);
    }
  }, [name]);

  const handleCreate = async () => {
    const nameValidation = validateWorkspaceName(name);

    if (!nameValidation.valid) {
      setNameError(nameValidation.error || "Invalid name");
      return;
    }

    setApiError(null);

    try {
      // Only send name, backend will generate unique slug
      const workspace = await createWorkspace.mutateAsync({
        name: name.trim(),
      });

      // Switch to the newly created workspace
      setSelectedWorkspaceId(workspace.id);
      handleClose();
    } catch (error: any) {
      console.error("Failed to create workspace:", error);
      const msg = error?.message || "";
      if (msg.includes("maximum of")) {
        setApiError(t("maxWorkspacesReached", { max: 3 }));
      } else {
        setApiError(msg || "Failed to create workspace. Please try again.");
      }
    }
  };

  const resetForm = () => {
    setName("");
    setSlugPreview("");
    setNameError(null);
    setApiError(null);
  };

  const handleClose = () => {
    resetForm();
    onClose();
  };

  const canCreate = name.trim() && !nameError;

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Building2 size={20} />
            Create a workspace
          </DialogTitle>
          <DialogDescription>
            Workspaces are where your team collaborates. Create one for your
            team, project, or organization.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {apiError && (
            <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm flex items-center gap-2">
              <AlertCircle size={16} />
              {apiError}
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="workspace-name">Name</Label>
            <Input
              id="workspace-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Acme Inc"
              autoFocus
              onKeyDown={(e) => {
                if (
                  e.key === "Enter" &&
                  canCreate &&
                  !createWorkspace.isPending
                ) {
                  e.preventDefault();
                  handleCreate();
                }
              }}
            />
            {nameError && (
              <p className="text-xs text-destructive flex items-center gap-1">
                <AlertCircle size={12} />
                {nameError}
              </p>
            )}
            {slugPreview && !nameError && (
              <p className="text-xs text-muted-foreground">
                URL: <span className="font-mono">{slugPreview}</span>
              </p>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button type="button" variant="ghost" onClick={handleClose}>
            Cancel
          </Button>
          <Button
            onClick={handleCreate}
            disabled={!canCreate || createWorkspace.isPending}
            className="bg-primary hover:bg-primary/90"
          >
            {createWorkspace.isPending ? "Creating..." : "Create Workspace"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
