import type { Resource, ResourceUsageLog } from "@/types/resource";

const TENANT_ID = "demo-tenant";
const CREATOR_ID = "demo-user";
const NOW = new Date();
const iso = (offsetMinutes: number) =>
  new Date(NOW.getTime() - offsetMinutes * 60_000).toISOString();

export const mockResources: Resource[] = [
  // ── Agent 计算机 ────────────────────────────────────────────────
  {
    id: "res-ac-001",
    tenantId: TENANT_ID,
    type: "agent_computer",
    name: "开发机 A",
    description: "本地 macOS 开发机，SSH 接入",
    config: {
      connectionType: "ssh",
      host: "192.168.1.100",
      port: 22,
      os: "macOS 14.5",
      arch: "arm64",
    },
    status: "online",
    authorizations: [
      {
        granteeType: "user",
        granteeId: "user-winrey-0001",
        permissions: { level: "full" },
        grantedBy: CREATOR_ID,
        grantedAt: iso(60 * 24 * 3),
      },
    ],
    lastHeartbeatAt: iso(2),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 10),
    updatedAt: iso(60 * 2),
  },
  {
    id: "res-ac-002",
    tenantId: TENANT_ID,
    type: "agent_computer",
    name: "生产沙箱机",
    description: "AWS us-east-1 弹性 Agent 沙箱",
    config: {
      connectionType: "cloud",
      host: "sandbox-prod.team9.internal",
      os: "Ubuntu 22.04",
      arch: "x86_64",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 15),
    updatedAt: iso(60 * 1),
  },

  // ── API ─────────────────────────────────────────────────────────
  {
    id: "res-api-001",
    tenantId: TENANT_ID,
    type: "api",
    name: "Tavily 搜索",
    description: "实时网页搜索 API",
    config: {
      provider: "tavily",
      apiKey: "tvly-1234567890abcdef",
      baseUrl: "https://api.tavily.com",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(5),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 7),
    updatedAt: iso(60 * 24),
  },
  {
    id: "res-api-002",
    tenantId: TENANT_ID,
    type: "api",
    name: "Stripe 支付",
    description: "账单与订阅 API",
    config: {
      provider: "stripe",
      apiKey: "sk_test_51Hxxxxxxxxxxxxxxxxxx",
      baseUrl: "https://api.stripe.com",
    },
    status: "offline",
    authorizations: [],
    lastHeartbeatAt: iso(60 * 6),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 20),
    updatedAt: iso(60 * 24 * 2),
  },

  // ── 大模型 / LLM ────────────────────────────────────────────────
  {
    id: "res-llm-001",
    tenantId: TENANT_ID,
    type: "llm",
    name: "GPT-4o",
    description: "OpenAI 主力推理模型",
    config: {
      provider: "openai",
      model: "gpt-4o",
      contextLength: 128_000,
      apiKey: "sk-openai-xxxxxxx",
    },
    status: "online",
    authorizations: [
      {
        granteeType: "task",
        granteeId: "task-gen-report",
        permissions: { level: "full" },
        grantedBy: CREATOR_ID,
        grantedAt: iso(60 * 24),
      },
    ],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 30),
    updatedAt: iso(60 * 3),
  },
  {
    id: "res-llm-002",
    tenantId: TENANT_ID,
    type: "llm",
    name: "Claude Opus 4.6",
    description: "Anthropic 长上下文旗舰",
    config: {
      provider: "anthropic",
      model: "claude-opus-4-6",
      contextLength: 1_000_000,
      apiKey: "sk-ant-xxxxxxx",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 5),
    updatedAt: iso(30),
  },

  // ── MCP 服务器 ───────────────────────────────────────────────────
  {
    id: "res-mcp-001",
    tenantId: TENANT_ID,
    type: "mcp",
    name: "Notion MCP",
    description: "通过 MCP 访问 Notion 工作区",
    config: {
      endpoint: "https://mcp.notion.com/sse",
      transport: "sse",
      tools: 12,
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(3),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 2),
    updatedAt: iso(60),
  },
  {
    id: "res-mcp-002",
    tenantId: TENANT_ID,
    type: "mcp",
    name: "Filesystem MCP",
    description: "本地文件系统 MCP，stdio 启动",
    config: {
      endpoint: "stdio://mcp-server-filesystem",
      transport: "stdio",
      tools: 6,
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(2),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 4),
    updatedAt: iso(60 * 4),
  },

  // ── 数据库 ──────────────────────────────────────────────────────
  {
    id: "res-db-001",
    tenantId: TENANT_ID,
    type: "database",
    name: "主业务 Postgres",
    description: "Team9 主数据库，只读副本接入",
    config: {
      engine: "postgres",
      host: "db-prod.team9.internal",
      port: 5432,
      database: "team9",
    },
    status: "online",
    authorizations: [
      {
        granteeType: "user",
        granteeId: "user-analytics-007",
        permissions: { level: "readonly" },
        grantedBy: CREATOR_ID,
        grantedAt: iso(60 * 12),
      },
    ],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 60),
    updatedAt: iso(60 * 6),
  },
  {
    id: "res-db-002",
    tenantId: TENANT_ID,
    type: "database",
    name: "缓存 Redis",
    description: "会话与限流计数器",
    config: {
      engine: "redis",
      host: "redis-prod.team9.internal",
      port: 6379,
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 60),
    updatedAt: iso(60 * 24),
  },

  // ── 浏览器 ──────────────────────────────────────────────────────
  {
    id: "res-br-001",
    tenantId: TENANT_ID,
    type: "browser",
    name: "Playwright 本地池",
    description: "预热的 Chromium 浏览器池",
    config: {
      kind: "playwright",
      version: "1.47.0",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(2),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 3),
    updatedAt: iso(60 * 2),
  },
  {
    id: "res-br-002",
    tenantId: TENANT_ID,
    type: "browser",
    name: "Browserbase 云浏览器",
    description: "远程浏览器即服务",
    config: {
      kind: "remote",
      endpoint: "wss://connect.browserbase.com",
      version: "chromium-120",
    },
    status: "configuring",
    authorizations: [],
    lastHeartbeatAt: null,
    creatorId: CREATOR_ID,
    createdAt: iso(60),
    updatedAt: iso(10),
  },

  // ── 知识库 ──────────────────────────────────────────────────────
  {
    id: "res-kb-001",
    tenantId: TENANT_ID,
    type: "knowledge_base",
    name: "产品知识库",
    description: "产品文档、FAQ、规格说明",
    config: {
      store: "qdrant",
      docs: 12840,
      dimensions: 1536,
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(5),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 45),
    updatedAt: iso(60 * 8),
  },
  {
    id: "res-kb-002",
    tenantId: TENANT_ID,
    type: "knowledge_base",
    name: "客户工单库",
    description: "历史工单与解决方案（pgvector）",
    config: {
      store: "pgvector",
      docs: 3572,
      dimensions: 1024,
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(5),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 20),
    updatedAt: iso(60 * 12),
  },

  // ── Sandbox ─────────────────────────────────────────────────────
  {
    id: "res-sb-001",
    tenantId: TENANT_ID,
    type: "sandbox",
    name: "E2B Python 沙箱",
    description: "代码执行 / 数据分析一次性沙箱",
    config: {
      provider: "e2b",
      runtime: "python",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(1),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 8),
    updatedAt: iso(30),
  },
  {
    id: "res-sb-002",
    tenantId: TENANT_ID,
    type: "sandbox",
    name: "Modal Node 沙箱",
    description: "Node.js 工具脚本运行环境",
    config: {
      provider: "modal",
      runtime: "node",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(2),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 4),
    updatedAt: iso(60),
  },

  // ── Webhook ─────────────────────────────────────────────────────
  {
    id: "res-wh-001",
    tenantId: TENANT_ID,
    type: "webhook",
    name: "GitHub 事件入站",
    description: "接收 GitHub push / PR 事件",
    config: {
      method: "POST",
      url: "https://hooks.team9.ai/github",
      secret: "whsec_abc...xyz",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(8),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 12),
    updatedAt: iso(60 * 2),
  },
  {
    id: "res-wh-002",
    tenantId: TENANT_ID,
    type: "webhook",
    name: "PagerDuty 告警",
    description: "值班告警流入",
    config: {
      method: "POST",
      url: "https://hooks.team9.ai/pagerduty",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(15),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 6),
    updatedAt: iso(60 * 5),
  },

  // ── 邮箱 & 日历 ─────────────────────────────────────────────────
  {
    id: "res-mc-001",
    tenantId: TENANT_ID,
    type: "mail_calendar",
    name: "Gmail 工作邮箱",
    description: "运营团队共享邮箱",
    config: {
      service: "gmail",
      account: "ops@team9.ai",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(3),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 25),
    updatedAt: iso(60 * 2),
  },
  {
    id: "res-mc-002",
    tenantId: TENANT_ID,
    type: "mail_calendar",
    name: "Google 日历",
    description: "创始人日程",
    config: {
      service: "google_calendar",
      account: "founder@team9.ai",
    },
    status: "online",
    authorizations: [],
    lastHeartbeatAt: iso(3),
    creatorId: CREATOR_ID,
    createdAt: iso(60 * 24 * 25),
    updatedAt: iso(60 * 2),
  },
];

export const mockUsageLogs: Record<string, ResourceUsageLog[]> = {
  "res-llm-001": [
    {
      id: "log-llm-001-1",
      resourceId: "res-llm-001",
      actorType: "agent",
      actorId: "agent-writer-42",
      taskId: "task-gen-report",
      executionId: "exec-8891",
      action: "api_call",
      metadata: { tokens: 3240 },
      createdAt: iso(5),
    },
    {
      id: "log-llm-001-2",
      resourceId: "res-llm-001",
      actorType: "agent",
      actorId: "agent-writer-42",
      taskId: "task-gen-report",
      executionId: "exec-8890",
      action: "api_call",
      metadata: { tokens: 1120 },
      createdAt: iso(17),
    },
  ],
  "res-mcp-001": [
    {
      id: "log-mcp-001-1",
      resourceId: "res-mcp-001",
      actorType: "agent",
      actorId: "agent-researcher-03",
      taskId: null,
      executionId: "exec-9901",
      action: "connect",
      metadata: null,
      createdAt: iso(12),
    },
  ],
  "res-db-001": [
    {
      id: "log-db-001-1",
      resourceId: "res-db-001",
      actorType: "user",
      actorId: "user-analytics-007",
      taskId: null,
      executionId: null,
      action: "connect",
      metadata: null,
      createdAt: iso(60),
    },
  ],
  "res-ac-001": [
    {
      id: "log-ac-001-1",
      resourceId: "res-ac-001",
      actorType: "agent",
      actorId: "agent-shell-01",
      taskId: "task-deploy",
      executionId: "exec-7712",
      action: "connect",
      metadata: null,
      createdAt: iso(8),
    },
  ],
};

export function getMockResource(id: string): Resource | undefined {
  return mockResources.find((r) => r.id === id);
}

export function getMockUsageLogs(id: string): ResourceUsageLog[] {
  return mockUsageLogs[id] ?? [];
}
