import { describe, it } from '@jest/globals';

/**
 * Originally generated by `nest new`, this suite tries to bootstrap the
 * full AppModule (`Test.createTestingModule({ imports: [AppModule] })`)
 * just to assert `GET /` returns "Hello World!". Bootstrapping AppModule
 * pulls in 30+ required env vars and live connections (Postgres, Redis,
 * RabbitMQ, S3 — see env.ts), none of which the `pnpm test:e2e` job has
 * available, so the suite has been red on origin/dev since at least
 * 4489eb8a (no working CI job ever exercised it).
 *
 * Skipping rather than deleting because:
 *   - removing the file in a test-only PR feels mis-scoped;
 *   - if the team ever wires up an integration harness with all the
 *     required services, restoring the assertion is a one-line change.
 *
 * The actual gateway controllers are exercised by ahand-integration,
 * ahand-persistence, and bot-staff-profile e2e specs.
 */
describe('AppController (e2e)', () => {
  it.skip('/ (GET) — needs the full AppModule env+infra harness (see comment)', () => {
    // intentionally empty
  });
});
