/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints/index'
import { Route as BatchTestIndexRouteImport } from './routes/batch-test/index'
import { Route as AgentAgentIdRouteImport } from './routes/agent/$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchTestIndexRoute = BatchTestIndexRouteImport.update({
  id: '/batch-test/',
  path: '/batch-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/batch-test': typeof BatchTestIndexRoute
  '/blueprints': typeof BlueprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/batch-test': typeof BatchTestIndexRoute
  '/blueprints': typeof BlueprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/batch-test/': typeof BatchTestIndexRoute
  '/blueprints/': typeof BlueprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent/$agentId' | '/batch-test' | '/blueprints'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent/$agentId' | '/batch-test' | '/blueprints'
  id: '__root__' | '/' | '/agent/$agentId' | '/batch-test/' | '/blueprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  BatchTestIndexRoute: typeof BatchTestIndexRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-test/': {
      id: '/batch-test/'
      path: '/batch-test'
      fullPath: '/batch-test'
      preLoaderRoute: typeof BatchTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  BatchTestIndexRoute: BatchTestIndexRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
