import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { useTranslation } from "react-i18next";
import { Upload } from "lucide-react";
import { wikisApi } from "@/services/api/wikis";

interface WikiCoverProps {
  wikiId: string;
  /**
   * Path of the cover image inside the wiki (folder9-relative). `null` →
   * render the gradient fallback. Values that aren't strings are coerced to
   * `null` by the caller (`WikiPageView`).
   */
  coverPath: string | null;
  editable?: boolean;
  isSaving?: boolean;
  onChangeCover?: (coverPath: string) => void;
  onUploadCover?: (file: File) => Promise<string>;
}

/**
 * Wide cover band at the top of a wiki page.
 *
 * The gateway's `/raw` endpoint is JWT-protected, so we can't just hand a
 * bare URL to `background-image: url(...)` — the browser wouldn't send our
 * bearer token. Instead we fetch the bytes through `wikisApi.getRawObjectUrl`
 * and render the resulting `blob:` URL. The object URL is revoked on
 * unmount / path change to avoid leaking memory.
 *
 * When no cover is configured, or when fetching fails, we fall back to a
 * neutral brand gradient so the header layout stays stable (the icon hangs
 * off the cover's lower edge and would look broken against a blank pane).
 */
export function WikiCover({
  wikiId,
  coverPath,
  editable = false,
  isSaving = false,
  onChangeCover,
  onUploadCover,
}: WikiCoverProps) {
  const { t } = useTranslation("wiki");
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [objectUrl, setObjectUrl] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  const [localUploading, setLocalUploading] = useState(false);

  useEffect(() => {
    if (!coverPath) {
      setObjectUrl(null);
      setFailed(false);
      return;
    }
    let cancelled = false;
    let created: string | null = null;
    setFailed(false);

    wikisApi
      .getRawObjectUrl(wikiId, coverPath)
      .then((url) => {
        if (cancelled) {
          URL.revokeObjectURL(url);
          return;
        }
        created = url;
        setObjectUrl(url);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
      if (created) URL.revokeObjectURL(created);
      setObjectUrl(null);
    };
  }, [wikiId, coverPath]);

  const hasImage = Boolean(coverPath && !failed && objectUrl);
  const isBusy = isSaving || localUploading;

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  const handleUploadChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file || !onUploadCover || !onChangeCover) return;
    if (!file.type.startsWith("image/")) {
      window.alert(
        t("coverPicker.imageOnly", {
          defaultValue: "Only image files can be used as covers.",
        }),
      );
      return;
    }

    setLocalUploading(true);
    try {
      const uploadedPath = await onUploadCover(file);
      onChangeCover(uploadedPath);
    } catch (error) {
      window.alert(
        error instanceof Error
          ? error.message
          : t("coverPicker.uploadFailed", {
              defaultValue: "Cover upload failed.",
            }),
      );
    } finally {
      setLocalUploading(false);
    }
  };

  return (
    <div
      data-testid={hasImage ? "wiki-cover-image" : "wiki-cover-fallback"}
      className="group relative h-32 bg-cover bg-center bg-gradient-to-br from-primary/30 via-blue-400/20 to-purple-400/20"
      // Quote the blob URL explicitly. Object URLs generated by
      // URL.createObjectURL() are safe (no user-controlled substring), but
      // quoting is cheap defensive hardening in case a future refactor
      // swaps in a user-controlled value — a bare `url(...)` would otherwise
      // allow CSS injection via crafted characters in the value.
      style={
        hasImage && objectUrl
          ? { backgroundImage: `url("${objectUrl}")` }
          : undefined
      }
    >
      {editable && onChangeCover && onUploadCover && (
        <div className="absolute right-6 bottom-4 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100">
          <input
            ref={fileInputRef}
            data-testid="wiki-cover-upload-input"
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleUploadChange}
          />
          <button
            type="button"
            aria-label={
              coverPath
                ? t("coverPicker.changeTriggerAria")
                : t("coverPicker.addTriggerAria")
            }
            data-testid="wiki-cover-picker-trigger"
            disabled={isBusy}
            onClick={handleUploadClick}
            className="inline-flex h-9 items-center gap-1.5 rounded-md border border-white/40 bg-background/90 px-2.5 text-sm text-foreground shadow-sm backdrop-blur transition-colors hover:bg-background disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Upload size={14} />
            <span>
              {isBusy
                ? t("coverPicker.uploading", { defaultValue: "Uploading..." })
                : coverPath
                  ? t("coverPicker.changeCover")
                  : t("coverPicker.addCover")}
            </span>
          </button>
        </div>
      )}
    </div>
  );
}
