//! Manages the local aHand daemon lifecycle.
//!
//! Workflow:
//! 1. Frontend calls `ahand_start` with the OpenClaw gateway URL and node_id.
//! 2. We write ~/.ahand/config.toml (openclaw-gateway mode).
//! 3. We spawn ahandd in the background.
//! 4. On logout / app exit, we kill the process.
//!
//! Node ID persistence:
//! A stable device ID is stored in ~/.ahand/team9-device-id so the same
//! node_id is reused across restarts. If the device was previously approved
//! by the OpenClaw gateway, it will reconnect without needing re-approval.

use std::process::{Child, Command};
use std::sync::Mutex;

static DAEMON: Mutex<Option<Child>> = Mutex::new(None);

/// Locate the aHand binary.
///
/// Search order:
/// 1. Tauri sidecar: binaries/ directory next to the app executable (Task 2.0).
/// 2. User-installed fallback: ~/.ahand/bin/ahandd.
/// 3. PATH fallback.
fn find_binary() -> Option<std::path::PathBuf> {
    // 1. Sidecar binary bundled next to the app executable (Tauri Task 2.0).
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let p = dir.join("ahandd");
            if p.exists() {
                return Some(p);
            }
        }
    }

    // 2. User-installed fallback: ~/.ahand/bin/ahandd.
    if let Some(home) = dirs::home_dir() {
        let p = home.join(".ahand").join("bin").join("ahandd");
        if p.exists() {
            return Some(p);
        }
    }

    // 3. PATH fallback.
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let p = dir.join("ahandd");
            p.exists().then_some(p)
        })
    })
}

/// Get or create a stable device ID stored in ~/.ahand/team9-device-id.
/// Reusing the same node_id allows the gateway to recognize a previously
/// approved device without requiring re-approval.
pub fn get_or_create_node_id() -> String {
    let path = dirs::home_dir()
        .expect("no home dir")
        .join(".ahand")
        .join("team9-device-id");

    if let Ok(id) = std::fs::read_to_string(&path) {
        let trimmed = id.trim().to_string();
        if !trimmed.is_empty() {
            return trimmed;
        }
    }

    // Generate a stable ID mixing timestamp + PID to avoid collisions
    // when multiple instances start simultaneously on the same machine.
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos();
    let pid = std::process::id();
    let id = format!("team9-{secs:016x}{pid:08x}{nanos:08x}");

    let _ = std::fs::create_dir_all(path.parent().unwrap());
    let _ = std::fs::write(&path, &id);
    id
}

/// Write ~/.ahand/config.toml for openclaw-gateway mode.
///
/// IMPORTANT: auth_token belongs under [openclaw] section, NOT at the top level.
fn write_config(
    gateway_url: &str,
    auth_token: Option<&str>,
    node_id: &str,
) -> std::io::Result<()> {
    let path = dirs::home_dir()
        .expect("no home dir")
        .join(".ahand")
        .join("config.toml");

    std::fs::create_dir_all(path.parent().unwrap())?;

    let (host, port, tls) = parse_gateway_url(gateway_url);

    // Build optional auth_token line — placed inside [openclaw] section.
    let auth_line = auth_token
        .map(|t| format!("auth_token = \"{t}\"\n"))
        .unwrap_or_default();

    let content = format!(
        r#"# Auto-generated by Team9 desktop app. Do not edit manually.
mode = "openclaw-gateway"

[openclaw]
gateway_host = "{host}"
gateway_port = {port}
gateway_tls = {tls}
node_id = "{node_id}"
{auth_line}"#
    );

    std::fs::write(&path, content)?;
    Ok(())
}

fn parse_gateway_url(url: &str) -> (String, u16, bool) {
    let tls = url.starts_with("wss://");
    let without_scheme = url
        .trim_start_matches("wss://")
        .trim_start_matches("ws://");

    // Strip path and query (e.g. "host.example.com/?token=abc" → "host.example.com")
    let authority = without_scheme
        .split_once('/')
        .map(|(a, _)| a)
        .unwrap_or(without_scheme)
        .split_once('?')
        .map(|(a, _)| a)
        .unwrap_or(without_scheme);

    if let Some((host, port_str)) = authority.rsplit_once(':') {
        let port = port_str.parse().unwrap_or(18789);
        return (host.to_string(), port, tls);
    }

    (authority.to_string(), 18789, tls)
}

/// Start aHand daemon in openclaw-gateway mode.
/// Kills any previously managed instance first.
pub fn start(gateway_url: &str, auth_token: Option<&str>, node_id: &str) -> Result<(), String> {
    stop(); // kill any previous managed instance

    let binary = find_binary()
        .ok_or_else(|| "aHand is not installed. Please install it first.".to_string())?;

    write_config(gateway_url, auth_token, node_id).map_err(|e| e.to_string())?;

    let config_path = dirs::home_dir()
        .unwrap()
        .join(".ahand")
        .join("config.toml");

    let child = Command::new(&binary)
        .arg("--config")
        .arg(&config_path)
        .spawn()
        .map_err(|e| format!("failed to spawn ahandd: {e}"))?;

    *DAEMON.lock().unwrap() = Some(child);
    Ok(())
}

/// Stop the daemon if we started it.
pub fn stop() {
    if let Some(mut child) = DAEMON.lock().unwrap().take() {
        let _ = child.kill();
        let _ = child.wait();
    }
}

/// Is the daemon process currently alive?
/// Note: true means the process exists, not necessarily that it is connected
/// to the gateway. Check device status via Team9 API for actual connectivity.
pub fn is_running() -> bool {
    DAEMON.lock().unwrap().is_some()
}

/// Read the cryptographic device ID from ~/.ahand/device-identity.json.
///
/// The device ID is the SHA256 hex of the Ed25519 public key generated by
/// ahandd. It is stable across restarts and matches the `deviceId` field
/// returned by the OpenClaw gateway's device list API.
///
/// Returns None if the identity file does not exist yet (daemon not started).
pub fn get_crypto_device_id() -> Option<String> {
    let path = dirs::home_dir()?
        .join(".ahand")
        .join("device-identity.json");
    let content = std::fs::read_to_string(path).ok()?;
    let v: serde_json::Value = serde_json::from_str(&content).ok()?;
    v["deviceId"].as_str().map(|s| s.to_string())
}
